name: Update plots

on:
    push:
        branches:
            - main
    schedule:
        - cron: '36 12 * * *'
    workflow_dispatch:

jobs:
    update-plots:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up python 3.7
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7

            - name: Install requirements
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt

            - name: Run update script
              run: python fetch.py

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: Update dataset and webpage
                commit_user_name: GitHub Actions
                commit_user_email: actions@github.com
                commit_author: GitHub Actions <actions@github.com>
                branch: main
 
