name: Update plots

on:
    push:
        branches:
            - main
    schedule:
        - cron: '50 18 * * *'
    workflow_dispatch:

jobs:
    update-plots:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up python 3.7.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7.9

            - name: Install requirements
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Generate plots
              run: |
                  python fetch.py
                  sed -i "s/\([0-9]\{4\}\)-\([0-9][0-9]\)-\([0-9][0-9]\)/$(date +"%Y-%m-%d")/g" README.md
            
            - name: Commit changes
              uses: EndBug/add-and-commit@v7
              with:
                  author_name: GitHub Actions
                  author_email: actions@github.com
                  message: 'Update plots'
                  add: '.'

