name: Update plots

on:
    push:
        branches:
            - main
    schedule:
        - cron: '30 17 * * *'
    workflow_dispatch:

jobs:
    update-plots:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up python 3.7.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7.9

            - name: Install requirements
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Generate plots
              run: |
                  python fetch.py
            
            - name: Evil git hack
              run: |
                 git fetch origin main
                 mv charts/$(date +"%Y-%m-%d")-*.png ..
                 git switch main
                 mv ../$(date +"%Y-%m-%d")-*.png charts/

            - name: Commit changes
              uses: EndBug/add-and-commit@v7
              with:
                  author_name: GitHub Actions
                  author_email: actions@github.com
                  message: 'Update plots'
                  add: '.'


#            - name: Commit changes
#              run: |
#                  ls -lt charts/
#                  git config --local user.email "actions@github.com"
#                  git config --local user.name "GitHub Actions"
#                  git add -A
#                  git commit -m 'Update plots' || echo "No changes to commit"
#                  git push origin || echo "No changes to commit"
